= BrainCube Language Specification
Kenneth Palmer <canicussoftware@gmail.com>
v1.0 2017-01-01

== What is BrainCube?
BrainCube is an esoteric programming language heavily inspired by https://esolangs.org/wiki/Brainfuck[brainf**k]. It was created as a side-project of mine during my freshman year of college, as a way for me to explore programming language design and implementation.

Notable features/quirks of BrainCube include:  

 * A memory system based in three dimensional space
 * Cells that have a capacity determined by their position in memory
 * User-defined pointers, which are used for executing all but two commands 
 * Three or four different control structures, depending on how you count them

== How does it work?

=== *Memory System*
Programming languages almost always treat memory like a one dimensional array, because that's more or less what it actually is at the level of assembly language. 

In BrainCube, the standard one-dimensional memory space used by most languages is mapped onto a three-dimensional memory space, called the _Memory Cube_. The three dimensional Memory Cube contains a list of two dimensional _sheets_. Each sheet contains a list of one dimensional _tapes_. Each tape contains a list of zero-dimensional _cells_, which actually hold data. 

Each cell can hold a number of bits equal to the index of its parent sheet in the Memory Cube plus one. For example, a cell on sheet 0 would contain 0+1=_1_ bit, a cell on sheet 1 would contain 1+1=_2_ bits, a cell on sheet 2 would contain 1+2=_3_ bits, and so on.

The only time a BrainCube program would directly control memory would be when it calls the `?` system command to trigger garbage collection. Otherwise, the implementer will automatically _allocate_ memory for new cells as needed. _The implementer will never deallocate/perform a garbage collection without receiving the `?` system command_. After reciving the `?` command, the implementer must deallocate any cell which meets both the following conditions:

 1. The cell must have a non-zero value.
 2. The cell must not have a role in keeping track of the positions of other non-zero cells.
 
*TL;DR:*

 * BrainCube has a 3D memory space.
 * A cell on sheet N can store N+1 bits.
 
=== *System Commands*
There are two system commands that are used to communicate with the interpreter directly, rather than to manipulate pointers. The two system commands are:  

 * `!`: Stop program execution  
 * `?`: Perform a garbage collection
  
=== *Pointers*
BrainCube, much like its predecessor https://github.com/quietsamurai98/MindMeld[MindMeld], can support multiple pointers. 
Unlike MindMeld, however, users of BrainCube may name and use their own pointers.  
 
Pointers are the heart and soul of BrainCube. Without any pointers, all a program could do is exit, or collect garbage it hasn't produced yet.
 
==== Pointer Declaration 
Pointers are declared by naming them without providing a list of commands for them to execute.

Pointer names may only contain letters, numbers, and underscores, and must contain at least one letter.

Example: `myptr`, followed by a space, newline, or tab would declare a new pointer named `myptr`, initialized so it is pointing at sheet 0, tape 0, cell 0, or [0][0][0] for short.

==== Pointer Commands
A pointer is told what to do by naming it and immediately following said name with a set of parentheses, containing a string of pointer commands, which are defined in the table below.

Example: `myptr(XX{plus}{plus}{plus}{plus}>{plus}{plus})` moves `myptr` to [2][0][0], sets that cell's value to 4, moves `myptr` to [2][0][1], then sets that value to 2.

[cols="a,d"] 
|===
2+| MOVEMENT COMMANDS
|`>`|Move the pointer to the right along the tape to the next cell.
|`<`|Move the pointer to the left along the tape to the previous cell.
|`^`|Move the pointer up the sheet to the next tape.
|`v`|Move the pointer down the sheet to the previous tape.
|`X`|Move the pointer forward through the Memory Cube to the next sheet.
|`O`|Move the pointer backward through the Memory Cube to the previous sheet.
2+| DATA MODIFICATION COMMANDS
|`{plus}`|Increase the pointer's target cell by one, wrapping to zero if need be.
|`-`|Decrease the pointer's target cell by one, wrapping to the cell's max value if need be.
2+| OUTPUT COMMANDS
|`.`|Output the value of the target cell as an ASCII character, without a newline.
|`'`|Output the value of the target cell in binary, followed by a newline.
|`:`|Output the value of the target cell as a base~10~ number, followed by a newline.
2+| INPUT COMMANDS
|`,`|Set the value of the target cell to an ASCII character entered in the console, no followed by a newline.
|`"`|Set the value of the target cell to a binary number entered in the console, followed by a newline.
|`;`|Set the value of the target cell to a base~10~ number entered in the console, followed by a newline.
|===

==== Pointer Scope
A pointer declared outside the body of a control flow structure is globally available to all code following the declaration.

A pointer declared inside the body of a control flow structure is available to all code that comes between the declaration and the end of the control flow structure.

=== Control Flow Structures
Control flow structures have two components, called the head and body. 

 * The head is the pair of parentheses containing the name of a pointer, and the contained pointer name. It is responsible for controlling the execution of the body's contents.
 * The body is the pair of brackets, and the code contained within said brackets. The type of body brackets determines the type of control flow structure.

==== If statements
 * Format: `(head){body}`  
 * Example: `(myptr){myptr(-)}` will decrement the value of myptr's target cell _if_ myptr's target cell is not equal to zero.  

==== While loops
 * Format: `(head)[body]`  
 * Example: `(myptr)[myptr(-)]` will decrement the value of myptr's target cell _while_ myptr's target cell is not equal to zero.  
 
==== Repeat Loops
   * Format: `(head)(body)` _or_ `(number)(body)`  
   * Examples: 
   ** `(ptr_a)(ptr_b({plus}))` will increment the value of ptr_b's target cell _n_ times, where _n_ is the value of ptr_a's target cell before first entering the repeat loop.  
   ** `(10)(myptr({plus}))` will increment the value of myptr's target cell 10 times.

=== Comments
All comments are block comments, and must start with `/\*` and end with `*/`. These comments may contain any text except for the substrings `/\*` or `*/`.
